#///////////////////////#
#    S T A R S H I P    #
#///////////////////////#
#     C O N F I G S     #
#///////////////////////#

# Add a line between prompts
add_newline = true

# MINIMAL OUTPUT 
format = "($directory)"

[directory]
disabled = false
home_symbol = "~"
format = "[$path](#f38ba8) \n[∮ ](#cdd6f4)"

# SHOW SOME INFO
# [hostname]
# ssh_only = false
# format = "[$hostname](bold blue) "
# disabled = false
 
# icons: >, λ,∮,∫,⌲,⋗,⇒,
# [character]
# success_symbol = "[∮](bold white)"
# error_symbol = "[∮](bold red)"

# [package]
# disabled = true

# [directory]
# style = "bold white"

# Battery
[battery]
full_symbol = "  "
charging_symbol = "  "
discharging_symbol = "  "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 20
style = "bold yellow"
discharging_symbol = " "

# Git 
[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_status]
conflicted = ""
ahead = '[](yellow)'
behind = ""
diverged = ""
up_to_date = '[](white)'
untracked = '[+\($count\)](yellow)'
stashed = ""
modified = '[](white)'
staged = '[+\($count\)](green)'
renamed = '[](white)'
deleted = "﯊"
